id: PDC935804
initial_creation_type: input
source_metadata:
  title: Works of Chomden Rigpe Raltri
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    748d:
      title: བཅོམ་ལྡན་རིག་རལ་གྱི་རྣམ་ཐར།
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 748d.txt
      order: 1
    5e7b:
      title: རྡོ་རྗེ་གདན་རྣམ་བཤད་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 5e7b.txt
      order: 2
    6fa1:
      title: བསྟན་པ་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 6fa1.txt
      order: 3
    6a95:
      title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེ་རྒྱན་རྣམ་པར་བཤད་པའི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 6a95.txt
      order: 4
    a90b:
      title: རྒྱུད་བླ་མའི་ཊཱིཀྐ་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: a90b.txt
      order: 5
    1e03:
      title: དབུ་མ་རྩ་ཤེས་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 1e03.txt
      order: 6
    c30c:
      title: རྣལ་འབྱོར་སྤྱོད་པ་བཞི་བརྒྱ་པ་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: c30c.txt
      order: 7
    6eb0:
      title: གྲུབ་མཐའ་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 6eb0.txt
      order: 8
    47a6:
      title: མངོན་པ་ཀུན་བཏུས་རྒྱན་གྱི་མེ་ཏོག
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: 47a6.txt
      order: 9
    e01f:
      title: དབུ་མ་རྒྱན་གྱི་རྣམ་པར་བཤད་པ་ཚིག་དོན་གསལ་བའི་མེ་ཏོག་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
      base_file: e01f.txt
      order: 10
created_at: '2022-04-06T16:51:21.673516'
last_modified_at: '2022-04-06T16:51:21.673523'
